### ISSUE TITLE
Message flashes : If you can see this...

### ISSUE THREAD

**Issue by tnedich** [jaing/react-page-transitions#1]
This message flashes in browser and then everything is "normal"

**If you can see this, something is broken (or JS is not enabled)!!.**

Does it have to happen. (Or something is wrong with my browser)

**Comment by jaing** [comment]
This is because an example is generated using yeoman. It adds this HTML to index file:

``` html
<div id="content">
    <h1>If you can see this, something is broken (or JS is not enabled)!!.</h1>
  </div>
```

Simply remove this HTML and react will override content of this div when it will mount the component. 

I also removed this html from demo page.
