### ISSUE TITLE
Previous page don't gets animated

### ISSUE THREAD

**Issue by qgustavor** [jaing/react-page-transitions#2]
As is on the code and can be seem with detail [in the animation](https://www.gif-explode.com/?explode=https://camo.githubusercontent.com/0925147e03c170601db800d13dbfa480ed728bb2/687474703a2f2f692e696d6775722e636f6d2f6a41454c49594d2e676966) the old page don't gets animated. It disrupts navigation a little.

Posting this issue because I got the same problem when implementing page transitions on a React application and I got interested on this project as maybe someone can know a solution to this problem.

**Comment by jaing** [comment]
I'm currently using react-router in projects. With current capabilities it may be hard to achiev. What router does is he replace a content whenever I'm switching views. 
In a past what I did when I was using Backbone.JS is i was storing views in seperate containers and destroing old view when animation was completed.
